name: Bug Report
description: Create a report to help us improve
title: "[BUG]"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: "Please follow the [troubleshooting steps](https://github.com/sunner/ChatALL#troubleshooting) before submitting a bug report. / 请在提交错误报告之前按照[故障排除步骤](https://github.com/sunner/ChatALL/blob/main/README_ZH-CN.md#%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3)进行操作。"
  - type: textarea
    attributes:
      label: Describe the bug / 描述问题
      description: |
        A clear and concise description of what the bug is.
        清晰简洁地描述问题是什么。
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce / 复现步骤
      description: |
        Steps to reproduce the behavior
        描述如何重现问题
      placeholder: |
        1. Go to / 转到 '...'
        2. Click on/点击 '....'
        3. Scroll down to / 滚动到 '....'
        4. See error / 出现错误
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior / 期望行为
      description: |
        A clear and concise description of what you expected to happen.
        清晰简洁地描述你期望发生的事情。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / 截图
      description: |
        If applicable, add screenshots to help explain your problem.
        如果需要，请添加截图以帮助解释你的问题。
    validations:
      required: false

  - type: textarea
    attributes:
      label: Devtools Info / 开发者工具信息
      placeholder: |
        In ChatALL menu, click View->Toggle Developer Tools to open devtools. Paste any suspicious info here.
        在 ChatALL 菜单中，点击“查看”->“切换开发者工具”来打开开发者工具。将任何可疑信息粘贴到这里。
    validations:
      required: true

  - type: input
    attributes:
      label: OS and version / 操作系统版本
      placeholder: Windows 11, Ubuntu Linux 22.04, macOS 13.3.1
    validations:
      required: true

  - type: input
    attributes:
      label: ChatALL version / ChatALL 版本
      placeholder: v1.36.53
    validations:
      required: true

  - type: input
    attributes:
      label: Network / 网络
      description: |
        Are you using a VPN or proxy?
        是否在使用 VPN 或代理？
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context / 其它相关信息
      description: |
        Add any other context about the problem here.
        在此添加有关问题的任何其他相关信息。
    validations:
      required: false
